version: "3"
# runs the entire refiner pipeline with all supporting services (including refiner) in docker
# set .env such that all services in docker are talking to each other only

services:
  ipfs-pinner:
    image: "us-docker.pkg.dev/covalent-project/network/ipfs-pinner:stable"
    volumes:
      - ~/.ipfs:/root/.ipfs/
    container_name: ipfs-pinner
    restart: always
    labels:
      "autoheal": "true"
    expose:
      - "3001:3001"
    environment:
      - W3_AGENT_KEY=${W3_AGENT_KEY}
      - W3_DELEGATION_FILE=/root/.ipfs/proof.out
    networks:
      - cqt-net
    ports:
      - "3001:3001"

  evm-server:
    image: "us-docker.pkg.dev/covalent-project/network/evm-server:stable"
    container_name: evm-server
    restart: always
    labels:
      "autoheal": "true"
    expose:
      - "3002:3002"
    networks:
      - cqt-net
    ports:
      - "3002:3002"

  refiner:
    image: "us-docker.pkg.dev/covalent-project/network/refiner:latest"
    container_name: refiner
    links:
      - "ipfs-pinner:ipfs-pinner"
      - "evm-server:evm-server"
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    depends_on:
      ipfs-pinner:
        condition: service_healthy
      evm-server:
        condition: service_healthy
    entrypoint: >
      /bin/bash -l -c "
        echo "moonbase-node:" $NODE_ETHEREUM_MAINNET;
        echo "evm-server:" $EVM_SERVER_URL;
        echo "ipfs-node:" $IPFS_PINNER_URL;
        cd /mix;
        MIX_ENV=dev mix release --overwrite;
        MIX_ENV=dev mix run --no-halt --eval 'Refiner.ProofChain.BlockSpecimenEventListener.start()';"
    environment:
      - NODE_ETHEREUM_MAINNET=${NODE_ETHEREUM_MAINNET}
      - BLOCK_RESULT_OPERATOR_PRIVATE_KEY=${BLOCK_RESULT_OPERATOR_PRIVATE_KEY}
      - EVM_SERVER_URL=${EVM_SERVER_URL}
      - IPFS_PINNER_URL=${IPFS_PINNER_URL}
      - BSP_PROOFCHAIN_ADDRESS=${BSP_PROOFCHAIN_ADDRESS}
      - BRP_PROOFCHAIN_ADDRESS=${BRP_PROOFCHAIN_ADDRESS}
      - PROOFCHAIN_CHAIN_ID=${PROOFCHAIN_CHAIN_ID}
    networks:
      - cqt-net
    ports:
      - "9568:9568" # prometheus metrics will be exported at http://localhost:9568/metrics etc.

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30

networks:
  cqt-net:
