version: '3'

services:
  node:
    image: "gcr.io/covalent-project/operational-staking:latest"
    container_name: eth-test-node
    restart:  on-failure
    expose:
      - 8545:8545
    entrypoint: ./entrypoint.sh
    networks:
      - cqt-net
    environment:
      - ERIGON_NODE=${ERIGON_NODE}
    ports:
      - 8545:8545

  cqt-virtnet:
    image: "gcr.io/covalent-project/operational-staking:latest"
    container_name: set-up-contracts
    restart: on-failure
    expose:
      - 8545:8545
    entrypoint:
      npm run docker:deploy
    depends_on:
      - node
    networks:
      - cqt-net

  # ipfs-pinner:
  #   image: "gcr.io/covalent-project/ipfs-pinner:latest"
  #   container_name: ipfs-pinner-instance
  #   restart:  on-failure
  #   expose:
  #     - 3000:3000
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - WEB3_JWT=${WEB3_JWT}

networks:
  cqt-net:
